export const RESOLUTION_IDEAS = [
  "Drink more water 💧",
  "Read 12 books 📚",
  "Walk 10,000 steps daily 🚶‍♀️",
  "Learn a new language 🗣️",
  "Cook dinner twice a week 🍳",
  "Start a gratitude journal 📔",
  "Call parents every Sunday 📞",
  "Reduce screen time 📵",
  "Meditate for 5 mins daily 🧘",
  "Save 10% of income 💰",
  "Learn to juggle 🤹",
  "Plant a small garden 🌿",
  "Go to bed by 11 PM 😴",
  "Quit sugar for a month 🍬",
  "Take more photos 📸",
  "Learn to play an instrument 🎸",
  "Volunteer once a month 🤝",
  "Drink green tea daily 🍵",
  "Write a letter to future self ✉️",
  "Explore a new city 🏙️",
  "Learn origami 🦢",
  "Do a handstand 🤸",
  "Run a 5K 🏃‍♂️",
  "Watch less TV 📺",
  "Declutter one room a month 📦",
  "Learn to code 💻",
  "Compliment a stranger daily 💖",
  "No takeout for a month 🥡",
  "Visit a museum 🏛️",
  "Learn to dance salsa 💃",
  "Wake up at 6 AM 🌅",
  "Start a side hustle 💼",
  "Eat more veggies 🥦",
  "Limit social media 📉",
  "Go camping ⛺",
  "Learn to paint 🎨",
  "Host a dinner party 🍽️",
  "Go for a solo trip ✈️",
  "Make your bed every morning 🛏️",
  "Listen to more podcasts 🎧",
  "Smile at everyone today 😊",
  "Take the stairs 🪜",
  "Learn calligraphy ✒️",
  "Bake a cake from scratch 🎂",
  "Go stargazing 🌌",
  "Adopt a plant 🌵",
  "Write a poem 📝",
  "Do random acts of kindness 🎁",
  "Stretch every morning 🙆‍♂️",
  "Learn a magic trick 🎩"
];

export const getRandomResolution = (): string => {
  const randomIndex = Math.floor(Math.random() * RESOLUTION_IDEAS.length);
  return RESOLUTION_IDEAS[randomIndex];
};